name: Test

on:
  pull_request:
    branches:
      - development
      - production
  push:
    branches:
      - development
      - production

jobs:
  test:
    name: Check that the library behaves as expected
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
